In [1]:


import numpy as np

x1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result = np.dot(x1,x2)
print(result)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [3]:
import numpy as np

x1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Initialize result matrix with zeros
result = [[0 for _ in range(len(x2[0]))] for _ in range(len(x1))]

# Perform matrix multiplication manually
for i in range(len(x1)):  # Rows of x1
    for j in range(len(x2[0])):  # Columns of x2
        for k in range(len(x2)):  # Common dimension
            result[i][j] += x1[i][k] * x2[k][j]

# Print the result
for row in result:
    print(row)


[300, 360, 420]
[660, 810, 960]
[1020, 1260, 1500]


In [9]:
import numpy as np

x1 = np.array([[1, 2, 3], [4, 5, 6]])

result= np.transpose(x1)
result

array([[1, 4],
       [2, 5],
       [3, 6]])